DROP SEQUENCE IF EXISTS church_and_religion_group;

CREATE SEQUENCE IF NOT EXISTS church_and_religion_group
INCREMENT 1
START 1;


ALTER TABLE churches_religions_dictionary ALTER COLUMN name TYPE varchar (255);
ALTER TABLE churches_religions_dictionary ALTER COLUMN name SET NOT NULL;


INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Świecki Ruch Misyjny Epifania', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Zrzeszenie Wolnych Badaczy Pisma Świętego w Rzeczypospolitej Polskiej', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Stowarzyszenie Badaczy Pisma Świętego w Polsce', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Chrześcijan Dnia Sobotniego', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Jednota Braci Polskich ', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Jezusa Chrystusa Świętych w Dniach Ostatnich w Polsce', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Związek Buddystów Zen', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Ewangeliczna Wspólnota Zielonoświątkowa', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Wolnych Chrześcijan w Rzeczypospolitej Polskiej', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Szkoła Zen Kwan Um w Polsce', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Chrystusowy w Polsce ', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Nowoapostolski w Polsce', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Buddyjski Związek Diamentowej Drogi Linii Karma Kagyu', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Stowarzyszenie Zborów Chrześcijan w Rzeczypospolitej Polskiej', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Związek Ajapa Yoga', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Chrześcijańska Wspólnota', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Związek Badaczy Biblii w Rzeczypospolitej Polskiej', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Lectorium Rosicrucianum Międzynarodowa Szkoła', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kanzeon Związek Buddyjski', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Światowy Uniwersytet Duchowy Brahma', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Ewangeliczny Związek Braterski w Rzeczypospolitej Polskiej', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościoł Chrystusowy w Rzeczypospolitej Polskiej', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Chrześcijan Wiary Ewangelicznej w Rzeczypospolitej Polskiej', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Ewangelicznych Chrześcijan w Rzeczypospolitej Polskiej', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Boży w Chrystusie', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Wspólnota Bez Bram Mumon - Kai Związek Buddyjski Zen Rinzai w Rzeczypospolitej Polskiej ', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Międzynarodowe Towarzystwo Świadomości Kryszny', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Uczniowie Ducha Świętego (Stowarzyszenie Panunistyczne)', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Buddyjska Wspólnota Zen Kannon', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Stowarzyszenie Jedności Muzułmańskiej', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Świadkowie Jehowy w Polsce', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Zjednoczeniowy Czyli Ruch pod  Wezwaniem Ducha Świętego Dla Zjednoczenia Chrześcijaństwa Światowego', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Ewangeliczny "Misja Łaski"', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Ruch Świadomości Babadżi Herakhandi Samadź', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Stowarzyszenie Chrześcijańskiej Nauki - Związek Wyznaniowy.', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Zbór Chrześcijański w Rzeczypospolitej Polskiej', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Centrum Biblijne "Jezus Jest Panem"', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Zbór w Wodzisławiu Śląskim', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Zbór Ewangelicko-Baptystyczny w Katowicach', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Zbór Ewangelicznych Chrześcijan w Duchu Apostolskim', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Chrześcijańska Wspólnotaewangeliczna', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Zbór Stanowczych Chrześcijan w Rzeczypospolitej Polskiej', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Adwentyści Dnia Siódmego Ruch Reformacyjny w Rzeczypospolitej Polskiej ', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Instytut Wiedzy O Tożsamości "Misja Czaitanii"', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Stowarzyszenie Muzułmańskie Ahmadiyya', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Reformowany Adwentystów Dnia Siódmego w Polsce ', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Międzynarodowa Misja "Centrum Służby Życia" – Life Centre Ministries', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Islamskie Zgromadzenie Ahl-Ul-Bayt', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Chrześcijański w Duchu Prawdy  Pokoju', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Radha Govind Society Of Poland', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Zachodni Zakon Sufi w Polsce', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Zbór Ewangeliczny "Agape" w Poznaniu Dwaj Starsi Zboru Łącznie', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Wspólnota Chrześcijańska "Pojednanie"', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Mesjańskie Zbory Boże (Dnia Siódmego)', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Chrześcijańska Wspólnota "Jezus Panem" Woj. Łódzkie', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Związek Wyznaniowy "Wierzę w Dobro Człowieka"', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Chrześcijański "Arka" w Poznaniu', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Ruch Chrześcijański Mt28', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Wiara Bahá''Í', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Zbór Wolnych Chrześcijan w Jaworznie', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Misja Pokoleń ', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Jezusa Chrystusa w Kamiennej Górze', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Związek Wyznaniowy Kwinarystów', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Ewangelicko-Prezbiteriański', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Medytacyjne Stowarzyszenie Najwyższej Mistrzyni Czing Hai w Polsce', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Jezusa Chrystusa w Werbkowicach', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół "Chrystus Dla Wszystkich" w Rzeczypospolitej Polskiej ', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Wspólnota Unitarian Uniwersalistów w Rzeczypospolitej Polskiej', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Zbór Ewangelii Łaski ', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Miłosiernego Boga ', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Związek Buddyjski Bencien Karma Kamtsang', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Zbór Ewangeliczny "Betel" w Warszawie', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół w Radomiu', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Wspólnota "Drzewo Oliwne"', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Międzynarodowa Wspólnota Dzogczen- Namdagling', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Chrześcijański Kościół Pełnej Ewangelii "Duch i Moc" ', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Chrześcijańska Wspólnota Mennonitów', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Rodzimy Kościół Polski ', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Chrześcijański Kościół Głosicieli Dobrej', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Misja Buddyjska – Trzy Schronienia w Polsce', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Polski Kościół Słowiański', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Boży ', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Ligmincha Polska', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Warszawski Kościół Chrystusowy', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Wspólnota Chrześcijańska Wrocław Dla Jezusa', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Misja Na Wschód We Wrocławiu', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Remonstrantów Polskich', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Boży w Polsce', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Pentakostalny w Rzeczypospolitej Polskiej', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Chrześcijański "Wieczernik" ', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Rodzima Wiara', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Starokatolicki w Rzeczypospolitej Polskiej', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Chrześcijański w Rypinie', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Chrześcijański w Warszawie', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Chrześcijański Kościół Dobra ', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Anglikański w Polsce ', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Centrum Chrześcijańskie "Nowa Fala"', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Panteistyczny "Pneuma"', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Społeczność Chrześcijańska "Miejsce', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Centrum Chrześcijańskie Kanaan', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Biblijny Kościół Baptystyczny', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Związek Buddyjski Dak Shang Kagyu w Polsce', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Chrześcijański Kościół "Maranatha" w Wiśle', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Unitariański', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Ursynowska Społeczność Ewangeliczna', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Polski Kościół Dialogu', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Chrześcijański Kościół "Dobra Nowina"', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół "Misja Dla Polski" ', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Chrześcijańskie Centrum "Pan Jest Sztandarem" - Kościół w Tarnowie ', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Polski Ewangeliczny Kościół Braterski w Tarnowskich Górach ', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Jezusa Chrystusa Wiary Chrześcijańskiej ', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Zakon Braci Zjednoczenia Energetycznego', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Nowego Przymierza ', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Ekklesia w Warszawie', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Jezusa Chrystusa Syjon w Rzeszowie', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Związek Wyznaniowy Eckankar w Polsce', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Chrześcijański Jezus', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Dom Izraela Polania', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Związek Buddystów Czan', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Chrześcijański Związek Wyznaniowy Źródło', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Miejscowy Kościół w Lublinie', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Mesjańska Społeczność Wywołanych', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Centrum Chrześcijańskie "Miecz Ducha"', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Zgromadzenie Braci i Sióstr Politeistów', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Chrześcijan w Rybniku ', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Lokalny Kościół w Kwidzynie', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Związek Wyznaniowy "Polska "Chrześcijańska Służba"""', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Chrześcijański Otwarte Drzwi', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Związek Hatha Jogi "Brama Jogi"', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Niezależna Gmina Wyznania Mojżeszowego', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Warsaw International Church', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Miłosierdzia Jezusowego', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Ewangeliczny w Rzeczypospolitej Polskiej', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Gmina Wyznaniowa Starozakonnych w Rzeczypospolitej Polskiej', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Chrześcijański "Słowo Wiary"', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Chwały', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Liga Muzułmańska w Rzeczypospolitej Polskiej', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Związek Taoistów Tao Te King', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Unia Ewangelikalna w Rzeczypospolitej Polskiej', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Ewangeliczny Kościół Chrześcijański', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Prezbiteriański ', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Armia Zbawienia w Rzeczypospolitej Polskiej', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Polski Narodowy Katolicki Kościół w Rzeczypospolitej Polskiej ', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Ormiański Kościół Apostolski w Rzeczypospolitej Polskiej', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Związek Wyznaniowy Singh Sabha Gurudwara w Rzeczpospolitej Polskiej', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Związek Wyznaniowy Hindu Bhavan w Rzeczypospolitej Polskiej ', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Instytut Śardza Ling', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Zrzeszenie Kościołów Chrystusowych w Rzeczypospolitej Polskiej Osoba Kierująca:Rada Krajowa Zrzeszenia', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Sangha "Dogen Zenji" ', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Beit Polska – Związek Postępowych Gmin Żydowskich', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Zachodniosłowiański Związek Wyznaniowy "Słowiańska Wiara" ', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Ormiański Kościoł Apostolski Katolikosatu Eczmiadzyńskiego w Rzeczypospolitej Polskiej', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Związek Tybetańskiego Bon "Sa Trik Er Sang"', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Związek Buddyjski  „Dzogczien Kunzang Cziuling”  w  Rzeczypospolitej Polskiej ', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Wyznawcy Słońca', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Staroprawosławna Cerkiew Staroobrzędowców  ', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Dobrej  Nadziei', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Katolicki Kosciół Narodowy w Polsce', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Związek Buddyjski „Yeshe Khorlo” w Rzeczypospolitej Polskiej', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Ośrodek Wietnamskiego Buddyzmu w Polsce', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Chrześcijański Zoe', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół „Chrześcijańska Wspólnota Jordan”', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Odrodzony Kościół Starokatolicki', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Ewangeliczny Kościół Metodystyczny w  Rzeczypospolitej Polskiej', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Boga Żywego, Będącego Wsparciem i Podporą Prawdy, Kościół Światło Świata', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Chrześcijan Pełnej Ewangelii Obóz Boży', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Reformowany Kościół Katolicki w Polsce', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Narodowy Kościół Katolicki', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Kościół Naturalny', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Polska Rada Ekumeniczna', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Towarzystwo Biblijne w Polsce', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Rada Zborów Ewangelicznych', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Polska Unia Buddyjska', false);
INSERT INTO churches_religions_dictionary (code, name, regulated_by_law) VALUES ('CHURCH_AND_RELIGION_GROUP_' || nextval('church_and_religion_group'),'Alians Ewangeliczny w Rzeczypospolitej Polskiej', false);


DROP SEQUENCE IF EXISTS church_and_religion_group;